// <auto-generated />
using System;
using MBSAdminApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MBSAdminApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250526040032_InitSQLite")]
    partial class InitSQLite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("MBSAdminApp.Models.Keuangan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("JenisTransaksi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Keterangan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Nominal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Keuangan");
                });

            modelBuilder.Entity("MBSAdminApp.Models.Pembelian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HargaPerKg")
                        .HasColumnType("TEXT");

                    b.Property<string>("JenisBahan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("JumlahKg")
                        .HasColumnType("REAL");

                    b.Property<string>("NamaPetani")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Wilayah")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pembelian");
                });

            modelBuilder.Entity("MBSAdminApp.Models.Penjualan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HargaPerKg")
                        .HasColumnType("TEXT");

                    b.Property<string>("JenisProduk")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("JumlahKg")
                        .HasColumnType("REAL");

                    b.Property<string>("NamaPembeli")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Penjualan");
                });

            modelBuilder.Entity("MBSAdminApp.Models.Produksi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BahanAwal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BahanHasil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JenisProses")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("JumlahAwalKg")
                        .HasColumnType("REAL");

                    b.Property<double>("JumlahHasilKg")
                        .HasColumnType("REAL");

                    b.Property<string>("NamaOperator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Produksi");
                });

            modelBuilder.Entity("MBSAdminApp.Models.Stok", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("JenisBahan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalKeluar")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalMasuk")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Stok");
                });
#pragma warning restore 612, 618
        }
    }
}
